import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    guidesSidebar: [{ type: 'autogenerated', dirName: '.' }],
    //   guidesSidebar: [
    //     {
    //       type: 'doc',
    //       id: 'intro',
    //       label: 'Введение',
    //     },
    //   ],
};

export default sidebars;